CXX ?= clang++
CC ?= cc
ENABLE_LTO ?= 1
ifeq ($(ENABLE_LTO),1)
  LTO_FLAGS = -flto
else
  LTO_FLAGS =
endif
CXXFLAGS = -std=c++17 -O2 -DNDEBUG $(LTO_FLAGS) -fvisibility=hidden -fvisibility-inlines-hidden
CFLAGS = -O2 -DNDEBUG $(LTO_FLAGS)
LDFLAGS = $(LTO_FLAGS)
PVAC_INCLUDE = -Ipvac/include -I. -Iinclude

# Embedded TLS recorder bundle (generated by scripts/build-bundle.sh)
BUNDLE_HEADER = include/tls_recorder_bundle.h

# Platform detection
UNAME := $(shell uname -s)
ARCH := $(shell uname -m)

# AES intrinsics (required by pvac LPN)
ifeq ($(ARCH),x86_64)
    AES_FLAGS = -maes -msse4.2
else ifeq ($(ARCH),amd64)
    AES_FLAGS = -maes -msse4.2
else ifneq (,$(filter aarch64 arm64,$(ARCH)))
    AES_FLAGS = -march=armv8-a+crypto
endif

ifeq ($(UNAME),Darwin)
    # macOS: OpenMP via Homebrew libomp (static link for code-signed distribution)
    LDFLAGS += -dead_strip
    OMP_FLAGS ?= -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include
    OMP_LIBS ?= /opt/homebrew/opt/libomp/lib/libomp.a
    # OpenSSL for relay TLS (static link for distribution; x86_64 cross-builds pass TLS_LIBS="" to skip)
    TLS_LIBS ?= /opt/homebrew/opt/openssl/lib/libssl.a /opt/homebrew/opt/openssl/lib/libcrypto.a
    TLS_INCLUDE ?= -I/opt/homebrew/opt/openssl/include
    TARGET = octane-accelerator
else ifeq ($(UNAME),Linux)
    LDFLAGS += -Wl,--gc-sections
    OMP_FLAGS = -fopenmp
    OMP_LIBS = -lpthread
    TLS_LIBS = -lssl -lcrypto
    TLS_INCLUDE =
    TARGET = octane-accelerator
else
    # Windows (MinGW) — static link for distribution
    LDFLAGS += -Wl,--gc-sections -static
    OMP_FLAGS = -fopenmp
    OMP_LIBS = -lws2_32 -lpthread -lbcrypt -lcrypt32 -lwinhttp -lshell32 -lole32
    TLS_LIBS = -lssl -lcrypto
    TLS_INCLUDE =
    TARGET = octane-accelerator.exe
    RC_OBJ = app_res.o
endif

CXX_SOURCES = main.cpp pvac/pvac_c_api.cpp
C_SOURCES = lib/tweetnacl.c lib/randombytes.c
HEADERS = src/server.hpp src/prover.hpp src/base64.hpp src/relay_bridge.hpp src/relay_client.hpp src/embedded_recorder.hpp $(BUNDLE_HEADER)

OBJS = tweetnacl.o randombytes.o

all: bundle $(TARGET)

# Build the TLS recorder bundle (embeds TS code in the binary)
bundle:
	@mkdir -p include
	@if [ ! -f $(BUNDLE_HEADER) ]; then \
		cd ../jolt-zktls && bash ../octane-accelerator/scripts/build-bundle.sh; \
		cp ../octane-accelerator/dist/tls_recorder_bundle.h $(BUNDLE_HEADER); \
	fi

# Force rebuild bundle (e.g. after updating TS code)
bundle-force:
	@mkdir -p include
	cd ../jolt-zktls && bash ../octane-accelerator/scripts/build-bundle.sh
	cp ../octane-accelerator/dist/tls_recorder_bundle.h $(BUNDLE_HEADER)

tweetnacl.o: lib/tweetnacl.c
	$(CC) $(CFLAGS) -c -o $@ $<

randombytes.o: lib/randombytes.c
	$(CC) $(CFLAGS) -c -o $@ $<

ifdef RC_OBJ
app_res.o: res/app.rc res/icon.ico
	windres res/app.rc -o app_res.o
endif

$(TARGET): $(CXX_SOURCES) $(HEADERS) $(OBJS) $(RC_OBJ)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(AES_FLAGS) $(OMP_FLAGS) $(PVAC_INCLUDE) $(TLS_INCLUDE) $(TLS_DEFINES) -o $@ $(CXX_SOURCES) $(OBJS) $(RC_OBJ) $(OMP_LIBS) $(TLS_LIBS) -lpthread
	strip $@

clean:
	rm -f $(TARGET) $(TARGET).exe *.o test_tls_recorder

# TLS recorder test binary
test_tls_recorder: test/test_tls_recorder.cpp $(HEADERS) $(OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(PVAC_INCLUDE) $(TLS_INCLUDE) $(JOLT_INCLUDE) -o $@ test/test_tls_recorder.cpp $(OBJS) $(JOLT_LIB) $(OMP_LIBS) $(TLS_LIBS) -lpthread -ldl -lm -liconv

# Record a TLS session and save to a JSON file for validation
# Usage: make test-tls-record HOST=example.com PORT=443
HOST ?= example.com
PORT ?= 443
test-tls-record: test_tls_recorder
	./test_tls_recorder $(HOST) $(PORT) > test_session.json 2>&1 || true
	@echo "Session saved to test_session.json"
	@echo "Validate with: cd ../jolt-zktls && npx tsx test/validate-session.ts ../octane-accelerator/test_session.json"

install: $(TARGET)
ifeq ($(UNAME),Darwin)
	cp $(TARGET) /usr/local/bin/
else ifeq ($(UNAME),Linux)
	cp $(TARGET) /usr/local/bin/
endif

.PHONY: all clean install
