/**
 * embedded_recorder.hpp — Extracts and runs the embedded TLS recorder bundle.
 *
 * On first call, extracts the embedded tar.gz to ~/.octane/tls-recorder/.
 * Node modules (including tsx) are pre-built in the bundle.
 * Then spawns `node tsx/dist/cli.mjs cli/prove-url.ts` with the target URL.
 *
 * Stderr from Node.js is parsed for status updates.
 * Stdout from Node.js is the JSON result.
 */

#pragma once

#include <string>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <cstdio>
#include <functional>
#include <thread>
#include <sys/stat.h>
#include "../lib/json.hpp"

// Embedded bundle data (generated by scripts/build-bundle.sh)
// Include this AFTER building the bundle.
#if __has_include("tls_recorder_bundle.h")
#include "tls_recorder_bundle.h"
#define HAS_EMBEDDED_BUNDLE 1
#else
#define HAS_EMBEDDED_BUNDLE 0
static const unsigned char tls_recorder_bundle[] = {};
static unsigned int tls_recorder_bundle_len = 0;
#endif

namespace octane {

using json = nlohmann::json;
using StatusCallback = std::function<void(const std::string&)>;

class EmbeddedRecorder {
public:
    std::string cache_dir;
    bool extracted = false;

    EmbeddedRecorder() {
#ifdef _WIN32
        const char* home = getenv("USERPROFILE");
        if (!home) home = "C:\\Users\\Default";
#else
        const char* home = getenv("HOME");
        if (!home) home = "/tmp";
#endif
        cache_dir = std::string(home) + "/.octane/tls-recorder";
    }

    /**
     * Ensure the bundle is extracted. Returns true on success.
     */
    bool ensure_extracted() {
        if (extracted) return true;

#if !HAS_EMBEDDED_BUNDLE
        fprintf(stderr, "[recorder] No embedded bundle (build with scripts/build-bundle.sh)\n");
        return false;
#else
        // Check if already extracted and up-to-date
        std::string marker = cache_dir + "/.extracted";
        std::ifstream check(marker);
        if (check.good()) {
            extracted = true;
            return true;
        }

        fprintf(stderr, "[recorder] Extracting bundle to %s...\n", cache_dir.c_str());

        // Create directory
        mkdir_recursive(cache_dir);

        // Write tar.gz
        std::string tar_path = cache_dir + "/bundle.tar.gz";
        {
            std::ofstream out(tar_path, std::ios::binary);
            if (!out) {
                fprintf(stderr, "[recorder] Failed to write bundle\n");
                return false;
            }
            out.write(reinterpret_cast<const char*>(tls_recorder_bundle),
                      tls_recorder_bundle_len);
        }

        // Extract (cross-platform)
#ifdef _WIN32
        std::string cmd = "cd /d " + cache_dir + " && tar -xzf bundle.tar.gz && del bundle.tar.gz";
#else
        std::string cmd = "cd " + cache_dir + " && tar -xzf bundle.tar.gz && rm bundle.tar.gz";
#endif
        if (system(cmd.c_str()) != 0) {
            fprintf(stderr, "[recorder] Failed to extract bundle\n");
            return false;
        }

        // Dependencies are already built in the bundled node_modules
        // (the build script runs npm install which builds tsx's dist/).
        // DO NOT run npm install here — it would trigger allow-scripts
        // policy which blocks esbuild postinstall and breaks tsx.
        std::string jolt_dir = cache_dir + "/jolt-zktls";

        // Mark embedded node binary as executable (may have lost permissions in extraction)
        std::string node_bin = cache_dir + "/node/node";
        if (file_exists(node_bin)) {
            chmod(node_bin.c_str(), 0755);
            fprintf(stderr, "[recorder] Embedded Node.js: %s\n", node_bin.c_str());
        }

        // Mark embedded jolt_prove as executable
        std::string jolt_prove = cache_dir + "/prove/target/release/jolt_prove";
        if (!file_exists(jolt_prove)) jolt_prove += ".exe"; // Windows
        if (file_exists(jolt_prove)) {
            chmod(jolt_prove.c_str(), 0755);
            fprintf(stderr, "[recorder] Embedded jolt_prove: %s\n", jolt_prove.c_str());
        }

        fprintf(stderr, "[recorder] Bundle extracted successfully\n");

        // Write marker
        {
            std::ofstream m(marker);
            m << "ok" << std::endl;
        }

        extracted = true;
        return true;
#endif
    }

    /**
     * Record a TLS session by running the embedded TS recorder.
     * Returns the session JSON, or a JSON object with "error" on failure.
     */
    json record(const std::string& url, const std::string& headers_json, const std::string& records_json, StatusCallback on_status) {
        if (!ensure_extracted()) {
            return json{{"error", "Failed to extract recorder bundle"}};
        }

        std::string jolt_dir = cache_dir + "/jolt-zktls";

        // Find the recorder script
        std::string script;
        if (file_exists(jolt_dir + "/cli/prove-url.js")) {
            script = jolt_dir + "/cli/prove-url.js";
        } else if (file_exists(jolt_dir + "/cli/prove-url.ts")) {
            script = jolt_dir + "/cli/prove-url.ts";
        } else {
            return json{{"error", "Recorder script not found in bundle"}};
        }

        // Determine how to run it
        // Use embedded Node.js if available, fall back to system node
#ifdef _WIN32
        std::string node_bin = normalize_path(cache_dir + "/node/node.exe");
#else
        std::string node_bin = cache_dir + "/node/node";
#endif
        if (!file_exists(node_bin)) {
            node_bin = "node"; // fallback to system node
        }

        // Set PATH to include embedded jolt_prove directory
        std::string jolt_prove_dir = normalize_path(cache_dir + "/prove/target/release");
#ifdef _WIN32
        std::string path_env = "set PATH=" + jolt_prove_dir + ";%PATH% && ";
#else
        std::string path_env = "PATH=" + jolt_prove_dir + ":$PATH ";
#endif

        // Cap rayon threads and increase stack size to avoid nested rayon pool
        // stack overflow (arkworks scalar_mul creates rayon pools inside workers).
        unsigned int cores = std::thread::hardware_concurrency();
        if (cores == 0) cores = 4;
        unsigned int rayon_threads = std::max(1u, cores / 2);
#ifdef _WIN32
        std::string env_prefix = "set RAYON_NUM_THREADS=" + std::to_string(rayon_threads)
                                + " && set RUST_MIN_STACK=67108864 && " + path_env;
#else
        std::string env_prefix = path_env
                                + "RAYON_NUM_THREADS=" + std::to_string(rayon_threads) + " "
                                + "RUST_MIN_STACK=67108864 ";
#endif
        std::string cmd;
        std::string norm_script = normalize_path(script);
        std::string headers_arg = headers_json.empty() ? "{}" : headers_json;
        std::string escaped_headers = shell_escape(headers_arg);
        std::string records_arg = records_json.empty() ? "" : " --records " + shell_escape(records_json);
        if (script.size() >= 3 && script.substr(script.size() - 3) == ".js") {
            cmd = env_prefix + shell_escape(node_bin) + " " + norm_script + " --url " + shell_escape(url) + " --headers " + escaped_headers + records_arg + " 2>&1";
        } else {
            // Use tsx from bundled node_modules
            std::string tsx = normalize_path(jolt_dir + "/node_modules/tsx/dist/cli.mjs");
            if (!file_exists(tsx)) {
                // Fallback: try .bin symlink or npx
                tsx = jolt_dir + "/node_modules/.bin/tsx";
                if (!file_exists(tsx)) tsx = "npx tsx";
            }
            cmd = env_prefix + shell_escape(node_bin) + " " + tsx + " " + norm_script + " --url " + shell_escape(url) + " --headers " + escaped_headers + records_arg + " 2>&1";
        }

        on_status("Recording TLS session...");

        fprintf(stderr, "[recorder] cmd: %s\n", cmd.c_str());

        // Run and capture output
        FILE* pipe = popen(cmd.c_str(), "r");
        if (!pipe) {
            return json{{"error", "Failed to spawn recorder process"}};
        }

        // Accumulate all output — prover JSON can be >100KB.
        // Parse status messages in real-time so the client WebSocket doesn't
        // idle-timeout during multi-minute zkTLS proofs.
        std::string all_output;
        std::string partial_line;
        std::string stdout_data;
        char buf[65536];
        while (fgets(buf, sizeof(buf), pipe)) {
            all_output += buf;
            partial_line += buf;
            // Process all complete lines in the partial buffer
            std::string::size_type pos;
            while ((pos = partial_line.find('\n')) != std::string::npos) {
                std::string line = partial_line.substr(0, pos);
                if (!line.empty() && line.back() == '\r') line.pop_back();
                partial_line.erase(0, pos + 1);
                try {
                    auto msg = json::parse(line);
                    if (msg.contains("status") && msg["status"].is_string()) {
                        std::string step = msg.value("step", "");
                        if (!step.empty()) on_status(step);
                        continue;
                    }
                    if (msg.contains("ok")) {
                        stdout_data = line;
                        continue;
                    }
                    if (msg.contains("error") && !msg.contains("ok")) {
                        pclose(pipe);
                        return msg;
                    }
                } catch (...) {
                    fprintf(stderr, "[recorder] non-json: %.200s\n", line.c_str());
                }
            }
        }
        // Handle any remaining partial line after process exits
        if (!partial_line.empty()) {
            if (partial_line.back() == '\r') partial_line.pop_back();
            if (!partial_line.empty()) {
                try {
                    auto msg = json::parse(partial_line);
                    if (msg.contains("ok")) stdout_data = partial_line;
                    else if (msg.contains("error") && !msg.contains("ok")) {
                        pclose(pipe);
                        return msg;
                    }
                } catch (...) {
                    fprintf(stderr, "[recorder] non-json: %.200s\n", partial_line.c_str());
                }
            }
        }

        int exit_code = pclose(pipe);

        if (exit_code != 0 && stdout_data.empty()) {
            return json{{"error", "Recorder exited with code " + std::to_string(exit_code)}};
        }

        if (stdout_data.empty()) {
            return json{{"error", "Recorder produced no output"}};
        }

        try {
            return json::parse(stdout_data);
        } catch (const std::exception& e) {
            return json{{"error", std::string("Failed to parse recorder output: ") + e.what()}};
        }
    }

private:
    static bool file_exists(const std::string& path) {
        struct stat st;
        return stat(path.c_str(), &st) == 0;
    }

    static void mkdir_recursive(const std::string& path) {
#ifdef _WIN32
        std::string cmd = "mkdir \"" + path + "\"";
#else
        std::string cmd = "mkdir -p " + path;
#endif
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-result"
        system(cmd.c_str());
#pragma GCC diagnostic pop
    }

    static std::string normalize_path(const std::string& s) {
#ifdef _WIN32
        std::string result = s;
        for (char& c : result) {
            if (c == '\\') c = '/';
        }
        return result;
#else
        return s;
#endif
    }

    static std::string shell_escape(const std::string& s) {
#ifdef _WIN32
        std::string result = "\"";
        for (char c : s) {
            if (c == '"') result += "\\\"";
            else result += c;
        }
        result += "\"";
        return result;
#else
        std::string result = "'";
        for (char c : s) {
            if (c == '\'') result += "'\\''";
            else result += c;
        }
        result += "'";
        return result;
#endif
    }
};

}  // namespace octane
